### ISSUE TITLE
iv

### ISSUE THREAD

**Issue by MangaKaroka** [py7hon/hide-directlink-gd#2]
I created key and api
but what is iv ?

**Comment by py7hon** [comment]
@MangaKaroka https://en.wikipedia.org/wiki/Initialization_vector

**Comment by deshitunes** [comment]
Hi, would you please guide me regarding this as below:
 $secret_key     = ' '; //your key
    $secret_iv      = ' '; //your iv

Api created....but above is not understanding....

**Comment by py7hon** [comment]
iv and key for encrypt and decrypt your id or Google Drive link

**Comment by deshitunes** [comment]
> iv and key for encrypt and decrypt your id or Google Drive link

Would you please guide about this or any video tutorial for your script. it would be great for me.
thanks for your times.

**Comment by py7hon** [comment]
> Would you please guide about this or any video tutorial for your script. it would be great for me.
thanks for your times.

you can create with random string like your create password and 2nd password

**Comment by deshitunes** [comment]
> > Would you please guide about this or any video tutorial for your script. it would be great for me.
> > thanks for your times.
> 
> you can create with random string like your create password and 2nd password

It's not working for me.
please generate it for me & send it : deshitunes@gmail.com

**Comment by py7hon** [comment]
Don forget to fill same string on generate.php and index.php

**Comment by deshitunes** [comment]
> Don forget to fill same string on generate.php and index.php
Sorry Dear, I've already tried several time but not works for me. that's why ask to you that generate for me & send to mail....please sir!

**Comment by py7hon** [comment]
like this:
```php
$secret_key     = 'wasd'; //your key
    $secret_iv      = '123'; //your iv
```
and don't forget to fill on index.php and generate.php

**Comment by deshitunes** [comment]
> like this:
> 
> ```
> $secret_key     = 'wasd'; //your key
>     $secret_iv      = '123'; //your iv
> ```
> 
> and don't forget to fill on index.php and generate.php

yes ,try that & it's showed 403

**Comment by py7hon** [comment]
can you screenshot the error ?

**Comment by deshitunes** [comment]
![image](https://user-images.githubusercontent.com/20432527/64860066-d3750c00-d64d-11e9-99d9-29cc6624fa30.png)

**Comment by py7hon** [comment]
the error id file on Google drive is limited for download, you can try another file

**Comment by deshitunes** [comment]
every links same as.... even from my own file...but same file is working on your demo. that's why humble request to you to generate a real key & iv for me & send it to my mentioned mail. thanks again.

**Comment by py7hon** [comment]
make `readfile()` ia enable on your server or cpanel

**Comment by deshitunes** [comment]
file permission 0755....same result....
ok sir...
thanks for your time.
