### ISSUE TITLE
high volume Bandwidth !

### ISSUE THREAD

**Issue by deshitunes** [py7hon/hide-directlink-gd#3]
Hi dev, Thanks for amazing script. Now arise a new issue as too much bandwidth are destroy the whole site. I mean that, its gather bandwidth from my hosting not google drive. please find out how we overcome bandwidth issue?
My 10 days bandwidth already gone as 450+GB. so, it's really hard to continue the script. but running too much download link from this script. please help...

**Comment by py7hon** [comment]
for bandwidth I suggest you use vps / server that uses unlimited bandwidth
